// seomaster/scripts/lib/research-saver.js

const fs = require('fs');
const path = require('path');

/**
 * 将 Google 搜索研究数据保存到 Obsidian vault
 * @param {string} keyword - 关键词
 * @param {Array} searchResults - 搜索结果
 * @param {Array} outlineData - 大纲数据
 * @param {string} vaultPath - Obsidian vault 路径
 * @returns {string} 保存的文件路径
 */
function saveResearchToVault(keyword, searchResults, outlineData, vaultPath) {
  if (!vaultPath || !fs.existsSync(vaultPath)) {
    console.warn('  ⚠️  Vault path not configured, skipping research save');
    return null;
  }

  const researchDir = path.join(vaultPath, 'Research');

  // 确保 Research 目录存在
  if (!fs.existsSync(researchDir)) {
    fs.mkdirSync(researchDir, { recursive: true });
  }

  // 按日期组织
  const date = new Date();
  const dateStr = date.toISOString().split('T')[0];
  const dateDir = path.join(researchDir, dateStr);

  if (!fs.existsSync(dateDir)) {
    fs.mkdirSync(dateDir, { recursive: true });
  }

  // 生成文件名
  const slug = keyword
    .toLowerCase()
    .replace(/[^a-z0-9\u4e00-\u9fa5]+/g, '-')
    .replace(/^-+|-+$/g, '');

  const timestamp = date.toISOString().replace(/[:.]/g, '-').slice(0, 19);
  const filename = `${slug}-${timestamp}.md`;
  const filepath = path.join(dateDir, filename);

  // 生成 Markdown 内容
  const content = generateResearchMarkdown(keyword, searchResults, outlineData, date);

  // 保存文件
  fs.writeFileSync(filepath, content, 'utf-8');

  return filepath;
}

/**
 * 生成研究数据的 Markdown 格式
 */
function generateResearchMarkdown(keyword, searchResults, outlineData, date) {
  const frontMatter = `---
type: research
keyword: ${keyword}
created: ${date.toISOString().split('T')[0]}
source: Google Search
results_count: ${searchResults.length}
successful_scrapes: ${outlineData.filter(o => !o.error).length}
---

`;

  let content = frontMatter;
  content += `# Research: ${keyword}\n\n`;
  content += `**Date**: ${date.toISOString().split('T')[0]}\n`;
  content += `**Results**: ${searchResults.length} URLs, ${outlineData.filter(o => !o.error).length} successfully scraped\n\n`;
  content += `---\n\n`;

  // 添加搜索结果列表
  content += `## Search Results\n\n`;
  searchResults.forEach((result, i) => {
    content += `### ${i + 1}. ${result.title}\n\n`;
    content += `- **URL**: ${result.url}\n`;
    content += `- **Description**: ${result.description || 'N/A'}\n\n`;
  });

  content += `---\n\n`;

  // 添加成功抓取的大纲
  content += `## Article Outlines\n\n`;

  outlineData.forEach((data, i) => {
    if (data.error) {
      content += `### ${i + 1}. ${data.title} ❌\n\n`;
      content += `- **URL**: ${data.url}\n`;
      content += `- **Error**: ${data.error}\n\n`;
    } else {
      content += `### ${i + 1}. ${data.title} ✓\n\n`;
      content += `- **URL**: ${data.url}\n`;
      content += `- **Outline**:\n\n`;

      if (data.outline && data.outline.length > 0) {
        data.outline.forEach(heading => {
          const indent = '  '.repeat(heading.level - 1);
          content += `${indent}- H${heading.level}: ${heading.text}\n`;
        });
      } else {
        content += `  (No outline extracted)\n`;
      }

      content += `\n`;
    }
  });

  content += `---\n\n`;
  content += `## Notes\n\n`;
  content += `- This research data was automatically generated by SEOMaster\n`;
  content += `- Use this data to understand competitor content strategies\n`;
  content += `- Update your knowledge base based on insights from this research\n\n`;

  return content;
}

/**
 * 检查是否应该保存研究数据
 */
function shouldSaveResearch(project) {
  return project && project.vault_path && project.save_research !== false;
}

module.exports = {
  saveResearchToVault,
  shouldSaveResearch,
};
